<div class="center-signin">
  <h1>SerieLast</h1>
  <p>Add an user to your installation</p>
  <?php if (isset($error)) { echo '<div class="alert alert-danger">' . $error . '</div>'; } ?>
  <?php if (isset($success)) { echo '<div class="alert alert-success">' . $success . '</div>'; } ?>
  <div>
    <form action="<?php echo APP_URL . '/install/addUser' ?>" method="post">
      <label class="sr-only">Name</label>
      <input name="name" type="text" placeholder="Name" class="form-control top" autofocus></input>
      <label class="sr-only">Password</label>
      <input name="pass" type="password" placeholder="Password" class="form-control"></input>
      <input type="submit" value="Add user" class="btn btn-lg btn-primary btn-block"></input><br />
    </form>
  </div>
  <a href="<?php echo APP_URL . '/install' ?>" class="btn btn-lg btn-primary btn-block">Back to install menu</a>
</div>
