<p> Add a user to serielast </p>
<?php if (isset($error)) { echo '<p>' . $error . '</p>'; } ?>
<?php if (isset($success)) { echo '<p>' . $success . '</p>'; } ?>
<form action="<?php echo APP_URL . '/install/addUser' ?>" method="post">
    <label>Name: </label><input name="name" type="text"></input><br />
    <label>Pass: </label><input name="pass" type="password"></input><br />
    <button type="submit">Add user</button><br />
</form>
<a href="<?php echo APP_URL . '/install' ?>"><button>Back to install menu</button></a>
