
		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="https://github.com/Tym17/SerieLast" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; SerieLast.</li><li>Credits: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</footer>

		<!-- Scripts -->
			<!--[if lte IE 8]><script src="<?php echo APP_URL . '/eventually/assets/js/ie/respond.min.js' ?>"></script><![endif]-->
			<script src="<?php echo APP_URL . '/eventually/assets/js/main.js' ?>"></script>

	</body>
</html>
