<!DOCTYPE HTML>
<!--
	Eventually by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>SerieLast: Setup</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="<?php echo APP_URL . '/eventually/assets/js/ie/html5shiv.js' ?>"></script><![endif]-->
		<link rel="stylesheet" href="<?php echo APP_URL . '/eventually/assets/css/main.css' ?>" />
		<link rel="stylesheet" href="<?php echo APP_URL . '/css/serielast.css' ?>" />
		<!--[if lte IE 8]><link rel="stylesheet" href="<?php echo APP_URL . '/eventually/assets/css/ie8.css' ?>" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="<?php echo APP_URL . '/eventually/assets/css/ie9.css' ?>" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1>SerieLast</h1>
				<p><?php echo $page_desc ?></p>
			</header>
