<p>Don't forget to set <strong>APP_INSTALLED</strong> to <strong>true</strong> once you are done </p>

<!-- Menu Buttons -->
<div>
  <a style="float: left; margin: 10px;" href="<?php echo APP_URL . '/install/populateDb' ?>"><button>Populate Db</button></a>
  <a style="float: left; margin: 10px;" href="<?php echo APP_URL . '/install/addUser' ?>"><button>Add user</button></a>
  <a style="float: left; margin: 10px;" href="<?php echo APP_URL ?>"><button>Back</button></a>
</div>
