<!-- Menu Buttons -->
<div class="center-signin">
  <a href="<?php echo APP_URL ?>"><h1>SerieLast</h1></a>
  <p style="text-align: justify;">Don't forget to set <strong>APP_INSTALLED</strong> to <strong>true</strong> once you are done.</p>
  <a href="<?php echo APP_URL . '/install/populateDb' ?>" class="btn btn-lg btn-primary btn-block">Populate Db</a>
  <a href="<?php echo APP_URL . '/install/addUser' ?>" class="btn btn-lg btn-primary btn-block">Add user</a>
  <a href="<?php echo APP_URL ?>" class="btn btn-lg btn-primary btn-block">Back</a>
</div>
