<!DOCTYPE HTML>
<!--
	Eventually by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>SerieLast: Setup</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="<?php echo APP_URL . '/eventually/assets/js/ie/html5shiv.js' ?>"></script><![endif]-->
		<link rel="stylesheet" href="<?php echo APP_URL . '/eventually/assets/css/main.css' ?>" />
		<!--[if lte IE 8]><link rel="stylesheet" href="<?php echo APP_URL . '/eventually/assets/css/ie8.css' ?>" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="<?php echo APP_URL . '/eventually/assets/css/ie9.css' ?>" /><![endif]-->
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<h1>SerieLast</h1>
				<p>Setup</p>
			</header>

		<!-- Menu Buttons -->
    <div>
      <a style="float: left; margin: 10px;" href="<?php echo APP_URL . '/install/populateDb' ?>"><button>Populate Db</button></a>
      <a style="float: left; margin: 10px;" href="<?php echo APP_URL . '/install/addUser' ?>"><button>Add user</button></a>
      <a style="float: left; margin: 10px;" href="<?php echo APP_URL ?>"><button>Back</button></a>
    </div>

		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; SerieLast.</li><li>Credits: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</footer>

		<!-- Scripts -->
			<!--[if lte IE 8]><script src="<?php echo APP_URL . '/eventually/assets/js/ie/respond.min.js' ?>"></script><![endif]-->
			<script src="<?php echo APP_URL . '/eventually/assets/js/main.js' ?>"></script>

	</body>
</html>
