<div class="center-signin">
  <a href="<?php echo APP_URL ?>"><h1>SerieLast</h1></a>
  <?php if (isset($error)): ?>
    <div class="alert alert-danger"><?php echo $error ?></div>
  <?php
    endif;
    if (isset($success)):
  ?>
    <div class="alert alert-success"><?php echo $success ?></div>
  <?php endif; ?>
  <a href="<?php echo APP_URL . '/install' ?>" class="btn btn-lg btn-primary btn-block">Back to install menu</a>
</div>
