<div class="center-signin">
  <h1>SerieLast</h1>
  <p>Edit a serie</p>
  <?php if (isset($error)) { echo '<div class="alert alert-danger">' . $error . '</div>'; } ?>
  <?php if (isset($success)) { echo '<div class="alert alert-success">' . $success . '</div>'; } ?>
  <div>
    <form action="<?php echo APP_URL . '/serie/edit' ?>" method="post">
      <label class="sr-only">Name</label>
      <input name="name" type="text" placeholder="Name" class="form-control" autofocus></input>
      <br/>
      <label>Last watched episode's season</label>
      <input name="season" type="number" value="0" class="form-control" autofocus></input>
      <label>Last watched episode</label>
      <input name="episode" type="number" value="0" class="form-control" autofocus></input>
      <label>Air day/Release day</label>
      <input name="airdate" type="text" placeholder="e.g: 'Friday' or '21/12/16'" class="form-control" autofocus></input>
      <br/>
      <input type="submit" value="Save" class="btn btn-lg btn-primary btn-block"></input><br />
    </form>
  </div>
  <a href="<?php echo APP_URL ?>" class="btn btn-lg btn-primary btn-block">Back</a>
</div>
