<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href=/static/css/app.39b8e519e0c76f5b578afd195015454e.css rel=stylesheet>
    <title>front</title>
  </head>
  <body>
    <a href="<?php echo APP_URL . '/login/out' ?>"><button>log out</button></a>
    <showcase img=http://deeragaming.net/wp-content/uploads/2014/12/AgentCarter-Volume1-4192.gif.jpg day=Friday episode=01 season=02 v-ref:case1></showcase>
    <showcase img=http://deeragaming.net/wp-content/uploads/2014/12/AgentCarter-Volume1-4192.gif.jpg day=Friday episode=01 season=02 v-ref:case1></showcase>
    <script type=text/javascript src=/static/js/manifest.4b509ada93c6bbc97f9f.js></script>
    <script type=text/javascript src=/static/js/vendor.b7ead83935fc28fcce66.js></script>
    <script type=text/javascript src=/static/js/app.159bec685ca91672692a.js></script>
  </body>
</html>
