<!DOCTYPE HTML>
<!--
	Multiverse by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Multiverse by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="<?php echo APP_URL . '/multiverse/assets/js/ie/html5shiv.js' ?>"></script><![endif]-->
		<link rel="stylesheet" href="<?php echo APP_URL . '/multiverse/assets/css/main.css' ?>" />
		<!--[if lte IE 9]><link rel="stylesheet" href="<?php echo APP_URL . '/multiverse/assets/css/ie9.css' ?>" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="<?php echo APP_URL . '/multiverse/assets/css/ie8.css' ?>" /><![endif]-->
	</head>
	<body>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
            <form action="<?php echo APP_URL . '/login/out' ?>">
						  <input value="Log out" type="submit"/>
            </form>
						<nav>
							<ul>
								<li><a href="#footer" class="icon fa-info-circle">About</a></li>
							</ul>
						</nav>
					</header>

				<!-- Main -->
					<div id="main">
						<article class="thumb">
							<a href="<?php echo APP_URL . '/install/addUser' ?>" class="image"><img src="images/thumbs/01.jpg" alt="" /></a>
							<h2>Magna feugiat lorem</h2>
						</article>

						<article class="thumb">
							<a href="images/fulls/01.jpg" class="image"><img src="images/thumbs/01.jpg" alt="" /></a>
							<h2>Add a serie</h2>
							<form method="post" action="#">
								<div class="field third first">
									<input type="text" name="name" placeholder="Name" />
								</div>
								<div class="field third">
									<input type="text" name="airday" placeholder="Air day" />
								</div>
								<div class="field third">
									<input type="text" name="progress" placeholder="Last episode seen" />
								</div>
								<ul class="actions">
									<li><input type="submit" value="Add" class="special" /></li>
									<li><input type="file" value="Change cover..." /></li>
								</ul>
							</form>
						</article>

					</div>

				<!-- Footer -->
					<footer id="footer" class="panel">
						<div class="inner split">
							<div>
								<section>
									<h2>SerieLast</h2>
									<p>Simple self hosted serie tracker.</p>
								</section>
								<section>
									<ul class="icons">
										<li><a href="https://github.com/Tym17/SerieLast" class="icon fa-github"><span class="label">GitHub</span></a></li>
									</ul>
								</section>
								<p class="copyright">
									&copy; SerieLast. Design: <a href="http://html5up.net">HTML5 UP</a>.
								</p>
							</div>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="<?php echo APP_URL . '/multiverse/assets/js/jquery.min.js' ?>"></script>
			<script src="<?php echo APP_URL . '/multiverse/assets/js/jquery.poptrox.min.js' ?>"></script>
			<script src="<?php echo APP_URL . '/multiverse/assets/js/skel.min.js' ?>"></script>
			<script src="<?php echo APP_URL . '/multiverse/assets/js/util.js' ?>"></script>
			<!--[if lte IE 8]><script src="<?php echo APP_URL . '/multiverse/assets/js/ie/respond.min.js' ?>"></script><![endif]-->
			<script src="<?php echo APP_URL . '/multiverse/assets/js/main.js' ?>"></script>
			<script src="<?php echo APP_URL . '/js/serielast.js' ?>"></script>
	</body>
</html>
