

<!-- Showcase block -->
<div class="row">
  <?php
    // User have no serie added
    if (empty($series)):
  ?>
    <div class="col-lg-12">
      <p>You don't have any serie. </p>
      <a href="<?php echo APP_URL . '/serie/add' ?>" class="btn btn-primary">Add one</a>
    </div>
  <?php
    endif;
    // Loop for each serie
    foreach ($series as $serie):
  ?>
  <!-- Single card -->
  <div class="col-lg-3">
    <div class="card card-outline-<?php echo $serie['Color'] ?>">
      <div class="card-block">
        <h4 class="card-title"><?php echo $serie['Name'] ?></h4>
        <p class="card-text lead">
          <span class="darker-main">S</span><?php echo $serie['LastSeason'] ?>
          <span class="darker-main">  E</span><?php echo $serie['LastEpisode'] ?></p>
        <p class="card-text">Coming back <?php echo $serie['AirDate'] ?></p>
        <a href="<?php echo APP_URL . '/serie/edit/' . $serie['id'] ?>" class="btn btn-<?php echo $serie['Color'] ?>">Edit</a>
      </div>
    </div>
  </div>
  <!-- End of a card -->
  <?php endforeach; ?>


</div>
</div>
<!-- End of Showcase -->

<!-- Navbar -->
<div class="my-nav">
  <div class="row">
    <div class="col-sm-2">
      <a href="<?php echo APP_URL . '/serie/add' ?>" class="btn btn-xs btn-primary btn-block ">Add a serie</a>
    </div>
    <div class="col-sm-2 offset-sm-8">
      <a href="<?php echo APP_URL . '/login/out' ?>" class="btn btn-xs btn-danger btn-block">Log out</a>
    </div>
  </div>
