

<!-- Showcase -->
<div class="row">

  <!-- Single card -->
  <div class="col-lg-3">
    <div class="card card-outline-primary">
      <div class="card-block">
        <h4 class="card-title">Serie Name</h4>
        <p class="card-text lead"><span class="darker-main">S</span>5<span class="darker-main">  E</span>10</p>
        <p class="card-text">Coming back Thursday</p>
        <a href="#" class="btn btn-primary">Edit</a>
      </div>
    </div>
  </div>
  <!-- End of a card -->


</div>
</div>
<!-- End of Showcase -->

<!-- Navbar -->
<div class="my-nav">
  <div class="row">
    <div class="col-sm-2">
      <a href="<?php echo APP_URL . '/serie/add' ?>" class="btn btn-xs btn-primary btn-block ">Add a serie</a>
    </div>
    <div class="col-sm-2 offset-sm-8">
      <a href="<?php echo APP_URL . '/login/out' ?>" class="btn btn-xs btn-danger btn-block">Log out</a>
    </div>
  </div>
