<?php if (isset($error)) { echo '<p>' . $error . '</p>'; } ?>
<div class="container">
  <div class="row">
    <div class=" col-md-4 col-md-offset-4">
      <form action="<?php echo APP_URL . '/login' ?>" method="post" class="form-horizontal">
        <div class="form-group">
          <label>Username</label><input type="text" name="user_name"></input>
        </div>
        <div class="form-group">
          <label>Password</label><input type="password" name="user_pass"></input>
        </div>
        <button type="submit">Log in</button>
      </form>
    </div>
  </div>
</div>
