<div class="center-signin">
  <h1>SerieLast</h1>
  <p>Log in</p>
  <?php if (isset($error)) { echo '<div class="alert alert-danger">' . $error . '</div>'; } ?>
  <form action="<?php echo APP_URL . '/login' ?>" method="post" class="sign_form">
    <input type="text" name="user_name" placeholder="Name" class="form-control"></input>
    <input type="password" name="user_pass" placeholder="Password" class="form-control"></input>
    <input type="submit" value="Log in" class="btn btn-lg btn-primary btn-block"></input>
  </form>
</div>
